# Generated by Django 2.0.7 on 2018-09-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zacklymain', '0004_auto_20180828_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='amountOfIncome',
            new_name='amountOfIncome1',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='item',
            new_name='item1',
        ),
        migrations.AddField(
            model_name='income',
            name='amountOfIncome2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='収入'),
        ),
        migrations.AddField(
            model_name='income',
            name='amountOfIncome3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='収入'),
        ),
        migrations.AddField(
            model_name='income',
            name='amountOfIncome4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='収入'),
        ),
        migrations.AddField(
            model_name='income',
            name='item2',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目'),
        ),
        migrations.AddField(
            model_name='income',
            name='item3',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目'),
        ),
        migrations.AddField(
            model_name='income',
            name='item4',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目'),
        ),
        migrations.AddField(
            model_name='income',
            name='precisely1',
            field=models.CharField(choices=[('za', 'zackly'), ('nz', 'notZackly')], default='za', max_length=2),
        ),
    ]
