# Generated by Django 2.0.7 on 2018-09-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zacklymain', '0005_auto_20180916_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedcost',
            old_name='amountOfFixedCost',
            new_name='amountOfFixedCost1',
        ),
        migrations.RenameField(
            model_name='fixedcost',
            old_name='item',
            new_name='item1',
        ),
    ]
