# Generated by Django 2.0.7 on 2018-09-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zacklymain', '0008_auto_20180918_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='balanceOfPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeName1', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfIncome1', models.IntegerField(blank=True, default=0, null=True, verbose_name='収入')),
                ('precisely1', models.CharField(choices=[('za', 'zackly'), ('nz', 'notZackly')], default='za', max_length=2)),
                ('incomeName2', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfIncome2', models.IntegerField(blank=True, default=0, null=True, verbose_name='収入')),
                ('incomeName3', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfIncome3', models.IntegerField(blank=True, default=0, null=True, verbose_name='収入')),
                ('incomeName4', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfIncome4', models.IntegerField(blank=True, default=0, null=True, verbose_name='収入')),
                ('fixedCostName1', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfFixedCost1', models.IntegerField(blank=True, default=0, null=True, verbose_name='固定')),
                ('fixedCostName2', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfFixedCost2', models.IntegerField(blank=True, default=0, null=True, verbose_name='固定')),
                ('fixedCostName3', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfFixedCost3', models.IntegerField(blank=True, default=0, null=True, verbose_name='固定')),
                ('fixedCostName4', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfFixedCost4', models.IntegerField(blank=True, default=0, null=True, verbose_name='固定')),
                ('fixedCostName5', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfFixedCost5', models.IntegerField(blank=True, default=0, null=True, verbose_name='固定')),
                ('fixedCostName6', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfFixedCost6', models.IntegerField(blank=True, default=0, null=True, verbose_name='固定')),
                ('fixedCostName7', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfFixedCost7', models.IntegerField(blank=True, default=0, null=True, verbose_name='固定')),
                ('fixedCostName8', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfFixedCost8', models.IntegerField(blank=True, default=0, null=True, verbose_name='固定')),
                ('fixedCostName9', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfFixedCost9', models.IntegerField(blank=True, default=0, null=True, verbose_name='固定')),
                ('fixedCostName10', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfFixedCost10', models.IntegerField(blank=True, default=0, null=True, verbose_name='固定')),
                ('spFixedCostName1', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfSpFixedCost1', models.IntegerField(blank=True, default=0, null=True, verbose_name='特別')),
                ('spFixedCostName2', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfSpFixedCost2', models.IntegerField(blank=True, default=0, null=True, verbose_name='特別')),
                ('spFixedCostName3', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfSpFixedCost3', models.IntegerField(blank=True, default=0, null=True, verbose_name='特別')),
                ('spFixedCostName4', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfSpFixedCost4', models.IntegerField(blank=True, default=0, null=True, verbose_name='特別')),
                ('spFixedCostName5', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='品目')),
                ('amountOfSpFixedCost5', models.IntegerField(blank=True, default=0, null=True, verbose_name='特別')),
            ],
        ),
        migrations.DeleteModel(
            name='FixedCost',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='SpFixedCost',
        ),
    ]
