# Generated by Django 2.0.7 on 2018-09-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zacklymain', '0009_auto_20180926_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceofpayment',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登録日'),
        ),
        migrations.AddField(
            model_name='balanceofpayment',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name='月'),
        ),
        migrations.AddField(
            model_name='balanceofpayment',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新日'),
        ),
        migrations.AddField(
            model_name='balanceofpayment',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfFixedCost1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='固定費金額1'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfFixedCost10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='固定費金額10'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfFixedCost2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='固定費金額2'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfFixedCost3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='固定費金額3'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfFixedCost4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='固定費金額4'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfFixedCost5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='固定費金額5'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfFixedCost6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='固定費金額6'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfFixedCost7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='固定費金額7'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfFixedCost8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='固定費金額8'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfFixedCost9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='固定費金額9'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfIncome1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='収入金額1'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfIncome2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='収入金額2'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfIncome3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='収入金額3'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfIncome4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='収入金額4'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfSpFixedCost1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='特別費金額1'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfSpFixedCost2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='特別費金額2'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfSpFixedCost3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='特別費金額3'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfSpFixedCost4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='特別費金額4'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='amountOfSpFixedCost5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='特別費金額5'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='fixedCostName1',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='固定費名1'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='fixedCostName10',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='固定費名10'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='fixedCostName2',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='固定費名2'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='fixedCostName3',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='固定費名3'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='fixedCostName4',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='固定費名4'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='fixedCostName5',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='固定費名5'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='fixedCostName6',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='固定費名6'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='fixedCostName7',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='固定費名7'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='fixedCostName8',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='固定費名8'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='fixedCostName9',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='固定費名9'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='incomeName1',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='収入名1'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='incomeName2',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='収入名2'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='incomeName3',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='収入名3'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='incomeName4',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='収入名4'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='spFixedCostName1',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='特別費1'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='spFixedCostName2',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='特別費2'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='spFixedCostName3',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='特別費3'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='spFixedCostName4',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='特別費4'),
        ),
        migrations.AlterField(
            model_name='balanceofpayment',
            name='spFixedCostName5',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='特別費5'),
        ),
    ]
