# Generated by Django 2.0.7 on 2018-09-30 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zacklymain', '0010_auto_20180930_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceofpayment',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日'),
        ),
    ]
